// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OEMEVWMS.Repositories.TinVT.Models;

public partial class ClaimProcessLogHoangTh
{
    public int ClaimProcessLogHoangThid { get; set; }

    public int WarrantyClaimHoangThid { get; set; }

    public string ActionTaken { get; set; }

    public DateTime? ActionDate { get; set; }

    public string PerformedBy { get; set; }

    public string Department { get; set; }

    public int? EstimatedHours { get; set; }

    public int? ActualHours { get; set; }

    public bool IsFinalStep { get; set; }

    public string Notes { get; set; }

    public virtual WarrantyClaimHoangTh WarrantyClaimHoangTh { get; set; }
}