// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace OEMEVWMS.Repositories.TinVT.Models;

public partial class PartTypeTinVt
{
    public int PartTypeTinVtid { get; set; }

    public string TypeCode { get; set; }

    public string TypeName { get; set; }

    public string Category { get; set; }

    public int SortOrder { get; set; }

    public DateTime EffectiveFrom { get; set; }

    public bool IsActive { get; set; }

    [JsonIgnore]
    public virtual ICollection<PartItemTinVt> PartItemTinVts { get; set; } = new List<PartItemTinVt>();
}