// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OEMEVWMS.Repositories.TinVT.Models;

public partial class PartItemTinVt
{
    public int PartItemTinVtid { get; set; }

    public int PartTypeTinVtid { get; set; }

    public string PartCode { get; set; }

    public string PartName { get; set; }

    public string SerialNumber { get; set; }

    public string Supplier { get; set; }

    public decimal? UnitPrice { get; set; }

    public int StockQuantity { get; set; }

    public int WarrantyMonths { get; set; }

    public DateTime? ManufacturedAt { get; set; }

    public bool IsActive { get; set; }

    public bool IsObsolete { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    public string Notes { get; set; }

    public virtual PartTypeTinVt PartTypeTinVt { get; set; }
}