// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OEMEVWMS.Repositories.TinVT.Models;

public partial class VehicleSupportInfoHienNpq
{
    public int VehicleSupportInfoHienNpqid { get; set; }

    public int BookingHienNpqid { get; set; }

    public string LicensePlate { get; set; }

    public string Color { get; set; }

    public string Notes { get; set; }

    public virtual BookingHienNpq BookingHienNpq { get; set; }
}