// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OEMEVWMS.Repositories.TinVT.Models;

public partial class WarrantyClaimHoangTh
{
    public int WarrantyClaimHoangThid { get; set; }

    public string Vin { get; set; }

    public string PartSerialNumber { get; set; }

    public DateTime? ClaimDate { get; set; }

    public string Status { get; set; }

    public string DiagnosisReport { get; set; }

    public string ImageUrl { get; set; }

    public virtual ICollection<ClaimProcessLogHoangTh> ClaimProcessLogHoangThs { get; set; } = new List<ClaimProcessLogHoangTh>();
}